# Copyright 2022 Synchronous Technologies Pte Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release & Publish

on:
  release:
    types: [created]

jobs:
  publish-to-npmjs:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #publish-to-github:
  #  runs-on: ubuntu-latest
  #  environment: Publish
  #  permissions:
  #    contents: read
  #    packages: write
  #  steps:
  #    - uses: actions/checkout@v3
  #    # Setup .npmrc file to publish to GitHub Packages
  #    - uses: actions/setup-node@v3
  #      with:
  #        node-version: "16.x"
  #        registry-url: "https://npm.pkg.github.com"
  #        # Defaults to the user or organization that owns the workflow file
  #        scope: "@zefhub"
  #    - run: yarn install
  #    - run: yarn build
  #    - run: yarn publish
  #      env:
  #        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
